### ISSUE TITLE
The list command throws and exception for both css and js

### ISSUE THREAD

**Issue by arisbartee** [cjohansen/juicer#1]
The list command throws and exception for both css and js

This is the exception output.  Sorry I don't have time to fix it myself.

$ juicer list html/stylesheets/game.css 
/Library/Ruby/Gems/1.8/gems/juicer-0.2.5/lib/juicer/command/list.rb:44:in `execute': private method`puts' called for #Logger:0x56c278 (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/juicer-0.2.5/lib/juicer/command/list.rb:40:in `each'
    from /Library/Ruby/Gems/1.8/gems/juicer-0.2.5/lib/juicer/command/list.rb:40:in`execute'
    from /Library/Ruby/Gems/1.8/gems/cmdparse-2.0.2/lib/cmdparse.rb:438:in `parse'
    from /Library/Ruby/Gems/1.8/gems/juicer-0.2.5/lib/juicer/cli.rb:27:in`parse'
    from /Library/Ruby/Gems/1.8/gems/juicer-0.2.5/lib/juicer/cli.rb:37:in `run'
    from /Library/Ruby/Gems/1.8/gems/juicer-0.2.5/bin/juicer:8
    from /usr/bin/juicer:19:in`load'
    from /usr/bin/juicer:19

**Comment by cjohansen** [comment]
Sorry about not replying, I though new issues would be sent by email, oops! Will fix soon.

**Comment by evocateur** [comment]
I have a fix for this in my fork, if you like.

**Comment by cjohansen** [comment]
Cool, I'll check it out and merge in this week. Thanks!

**Comment by cjohansen** [comment]
This was closed a while back
