### ISSUE TITLE
Cache buster not working?

### ISSUE THREAD

**Issue by skyzyx** [cjohansen/juicer#10]
Here's the command I'm using:

<pre>
juicer merge \
    --absolute-urls \
    --cache-buster hard \
    --skip-verification \
    --hosts http://cdn1.domain.com,http://cdn2.domain.com \
    --ignore-problems \
    --force \
    --document-root / \
    --all-hosts-local \
    --output ./public/styles/chrome.min.css \
    ./public/styles/chrome.css;
</pre>

I'm expecting to look through the resulting CSS file and see timestamps appended to the filenames for external images. Am I expecting the correct thing, or is the cache buster broken?

**Comment by cjohansen** [comment]
Your expectation is quite correct, however it's hard to tell you exactly why it isn't working without seeing your source files. From the look of it you might have misunderstood the document-root option. It's supposed to tell Juicer which directory on your disk is served as the root resource. If your site lives in /var/www/yoursite/ then perhaps your document root would be /var/www/yoursite/public. It's used by Juicer to resolve URLs like "/images/logo.png" to a full file path. From the look of your example, I'd advice you to try --document-root ./public.

By the way: you don't need --ignore-problems when you --skip-verification :)

**Comment by cjohansen** [comment]
Closing
