### ISSUE TITLE
Juicer not compatible with Ruby 1.9

### ISSUE THREAD

**Issue by jakubpawlowicz** [cjohansen/juicer#13]
Once installing juicer on Ruby 1.9 I'm getting the following error:

/usr/local/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.1/lib/zip/zip.rb:4:in `require': no such file to load -- ftools (LoadError)
    from /usr/local/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.1/lib/zip/zip.rb:4:in`<top (required)>'
    from /usr/local/lib/ruby/gems/1.9.1/gems/juicer-0.2.6/lib/juicer/install/jslint_installer.rb:3:in `require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/juicer-0.2.6/lib/juicer/install/jslint_installer.rb:3:in`<top (required)>'
    from /usr/local/lib/ruby/gems/1.9.1/gems/juicer-0.2.6/lib/juicer.rb:62:in `require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/juicer-0.2.6/lib/juicer.rb:62:in`block in require_all_libs_relative_to'
    from /usr/local/lib/ruby/gems/1.9.1/gems/juicer-0.2.6/lib/juicer.rb:62:in `each'
    from /usr/local/lib/ruby/gems/1.9.1/gems/juicer-0.2.6/lib/juicer.rb:62:in`require_all_libs_relative_to'
    from /usr/local/lib/ruby/gems/1.9.1/gems/juicer-0.2.6/lib/juicer.rb:67:in `<top (required)>'
    from /usr/local/lib/ruby/gems/1.9.1/gems/juicer-0.2.6/bin/juicer:5:in`require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/juicer-0.2.6/bin/juicer:5:in `<top (required)>'
    from /usr/local/bin/juicer:19:in`load'
    from /usr/local/bin/juicer:19:in `<main>'

In 1.9 ftool were removed in favor to fileutils.

**Comment by cjohansen** [comment]
It's the zip gem that fails I think. It's on my list.

**Comment by jakubpawlowicz** [comment]
Yes, you are right. I found a workaround by using http://github.com/febeling/rubyzip

**Comment by cjohansen** [comment]
Thanks. My tests for the upcoming 1.0 release looks like they're all green on 1.9, except for one insignificant test.

**Comment by jakubpawlowicz** [comment]
1.0 release? Looking forward to it!

**Comment by cjohansen** [comment]
Closed
