### ISSUE TITLE
Allow depending on directories

### ISSUE THREAD

**Issue by ktheory** [cjohansen/juicer#17]
Please add support for depending on a directory. When a resolver encounters a dependency that's a directory, recursively include all js/css files in that directory.

I have patch on a feature branch (with tests) at http://github.com/ktheory/juicer/tree/directory_resolver

Here's the motivation: In development, it's useful and common to break big packages into logical subcomponents. E.g.

```
my-package/
my-package/my-package.js
my-package/module1.js
my-package/modules2.js
my-package/submodule/submodule1.js
my-package/submodule/submodule2.js
```

Currently, if `my-app.js` depends on my-package, developers must enumerate every js file in my-package as a dependency. If you add a file to my-package, you must add the dependency to `my-app.js` and other files that depend on my-package.

It's simpler to say in `my-app.js`:

```
// @depend my-package
```

With this patch, juicer notices `my-package` is a directory, globs for files like `my-package/**/*.js`, and adds each of those files as a dependency. Since the resolver is recursive, dependencies within & between the files of my-package are naturally resolved.

Depending on css packages works similarly:

```
@import('my-package')
```

Unfortunately, this isn't valid CSS until juicer parses it. I'm not sure how important that is. The fact that css imports work without juicer seems somewhat incidental, since js _does_ need juicer to resolve dependencies.

Anyway, this is a useful feature for my js projects. Would it be useful to others?

**Comment by cjohansen** [comment]
That is very cool, Aaron! I've pulled, run tests and confirmed that this is some good stuff :) It's pushed to my repo now. I think 1.0 release is approaching. Thanks alot! Please don't hesitate if you have other ideas as well.

**Comment by yeraycaballero** [comment]
Hi Christian, 
It's possible use a root directory in @depends?

I'm trying to avoid paths like @depends ../../../foo.js. I would like write something like
@depends $root/views/view.js
@depends $root/control/commands/command.js

**Comment by cjohansen** [comment]
yeraycaballero: No, sorry not at the moment. That would be interesting though.
