### ISSUE TITLE
Fixed warning about already initialized constant

### ISSUE THREAD

**Issue by ktheory** [cjohansen/juicer#18]
Right now there's a warning when requiring juicer:

`juicer/cache_buster.rb:68: warning: already initialized constant DEFAULT_PARAMETER`

It's because Juicer.require_all_libs_relative_to(**FILE**) is requiring the expanded paths, and other files require relative paths. I refactored Juicer.require_all_libs to require relative paths.

http://github.com/ktheory/juicer/tree/fix_constant_warning

**Comment by cjohansen** [comment]
Thanks! Merged in.
