### ISSUE TITLE
Debug mode for JavaScript

### ISSUE THREAD

**Issue by skyzyx** [cjohansen/juicer#2]
Is there any way to concatenate JavaScript without compressing it? It'd be useful for debugging JavaScript in Firebug line-by-line without having to include the files into my pages manually.

**Comment by cjohansen** [comment]
Sure, you can just skip the minifyer with the -m/--minifyer option:
 `juicer merge -m none myfile.js`

(Sorry about the late reply, I though new issues would be sent by email, oops!)
