### ISSUE TITLE
Bug in stylesheet_merger.rb

### ISSUE THREAD

**Issue by DallanQ** [cjohansen/juicer#20]
First, THANK YOU for creating this terrific tool!

I found an issue in stylesheet_merger.rb around line 62.  

You currently have

content.gsub!(/(#{url})/m, "(#{path})") unless path == url

But this doesn't work with quoted urls.  You should have

content.gsub!(/([\s"']_#{url}[\s"']_)/m, "(#{path})") unless path == url

or

content.gsub!(url, path) unless path == url

**Comment by DallanQ** [comment]
It looks like markdown removed the asterisks in my post.  There should be an asterisk after each of the [\s"'] expressions in my suggested fix.

**Comment by cjohansen** [comment]
Thanks, Dallan! I've fixed this now, will release 1.0.3 shortly.
