### ISSUE TITLE
Compiling with closure_compiler

### ISSUE THREAD

**Issue by shiki** [cjohansen/juicer#22]
Hi! Thanks for this awesome tool! How do you compile using closure_compiler? I tried:

juicer  merge js/min/common.js -s -f -m closure_compiler

But I'm getting this error:

"-js_output_file" is not a valid option

**Comment by dewski** [comment]
I get this as well, just to note.

**Comment by cjohansen** [comment]
Thanks, I'll look into it. In the meantime, try with an older version of the Google Closure Compiler.

**Comment by Monokai** [comment]
Just to let you know I'm having the same issue. Tried on all 1.x versions and they all display this error.

**Comment by cjohansen** [comment]
This issue is now solved. Juicer 1.0.4 is pushed to gem servers, and should be available shortly.
