### ISSUE TITLE
http://www.jslint.com/rhino/jslint.js has been removed

### ISSUE THREAD

**Issue by ileitch** [cjohansen/juicer#26]
Hi, the JsLint author has removed http://www.jslint.com/rhino/jslint.js which now causes juicer install jslint to fail. See this commit: https://github.com/douglascrockford/JSLint/commit/523956b6a2a6771ecfdd138934ed0611fb25bc6c

**Comment by cjohansen** [comment]
Ah, that sucks. As a temporary fix I bundled the file for now. Pushing 1.0.9 as we speak.

**Comment by ivanchoff** [comment]
:( i need it
