### ISSUE TITLE
sprockets-style require functionality

### ISSUE THREAD

**Issue by costa** [cjohansen/juicer#27]
I'm working on some sort of browser extension, and as such it needs its javascript (embeddable in _any_ web page) as self-contained and non-interfering as possible.
Currently, I use sprockets, and my main javascript begins with:
    //= require <jquery>
    var __jQj = $;
    $.noConflict(true)(function()
    { var $ = __jQj; var jQuery = __jQj;
    //= require <jquery.cookie>
    //= require <jquery.hoverIntent>
    ...

As you can see, all of the code (and there are quite a bunch of requires) sits within a private scope. As far as I understand, this is not easily possible with juicer which I tend to consider as an otherwise better option for my development.
Can you please try to suggest a solution for the above setup?

**Comment by cjohansen** [comment]
This is something I'm interested in myself, so I'll have a look at it. Do you mind sharing why you feel Juicer is a better fit for you than Sprockets?

**Comment by cjohansen** [comment]
Had a look. Unfortunately, this is not easily achievable without rewriting parts of Juicer. Currently Juicer does the following:

1) Figure out dependencies
2) Write all dependencies to output in correct order

With interleaved includes the rules for circular requirements change, and a partial rewrite is needed to complete this task. I'm afraid I won't have time for that anytime soon, but I'd love to assist if you want to take a stab at it.

**Comment by costa** [comment]
Thanks for your attention and your work. Unfortunately, I've spent too much time with JS recently, and it's tiring like hell, so I'll try to avoid touching anything JS-related anytime soon.
I hope a solution for this issue will come up eventually, meanwhile, I'll stick to sprockets.
Regarding the preference, Juicer looks more powerful than sprockets -- with the latter having a single-JS-per-app config, stupid yamls, overall API deficiency etc (no offence though, it does its job well in simple/most cases) -- but I'd like to make any conclusions when I have a chance to actually use Juicer.
