### ISSUE TITLE
Option to skip certain files from JsLint when you run merge

### ISSUE THREAD

**Issue by olleolleolle** [cjohansen/juicer#29]
Extracted this feature request from another Issue. And, I want it.

**Comment by cjohansen** [comment]
Hmm, what would that look like? How about running juicer verify separately and minify with -s (skip minifyer)?

**Comment by olleolleolle** [comment]
Weeeeell, that is what I ended up doing. Perhaps this is just a tactic that needs to be advertised as soon as possible to the user. So that I don't end up complaining like this.
