### ISSUE TITLE
Merging but not minifying JS

### ISSUE THREAD

**Issue by mattfordham** [cjohansen/juicer#31]
After running the following command (-s because the jsLint settings don't seem to like Coffeescript generated JS), my files get merge but not minified. I get a 'Unable to access jarfile' message. Maybe that has something to do with it? YUI Compressor is installed, as directed by the instructions.

juicer merge -s  main.js

Thanks for any help.

**Comment by cjohansen** [comment]
What is the path to the YUI compressor file? Are you by chance on Windows?

**Comment by mattfordham** [comment]
I'm on OSX. The YUI compressor is in ~/.juicer/lib/yui_compressor.

**Comment by cjohansen** [comment]
And you verified that the file was there? YUI has been moving it around lately, maybe your install failed? I just pushed a new version. Try removing ~/.juicer and then `gem update juicer` and then `juicer install yui_compressor`.

**Comment by mattfordham** [comment]
That fixed it, thanks!

**Comment by cjohansen** [comment]
Great!

**Comment by AlexSkrypnyk** [comment]
Actually, there is another question here: how to deliberately merge and not minify (aka aggregate)? 
UPDATE: Just found an answer in issue #28
To disable minification and use combining/aggregation of files use`--minifyer ""`
