### ISSUE TITLE
Unable to install Juicer on OS X (Snow Leopard)

### ISSUE THREAD

**Issue by ratmat2000** [cjohansen/juicer#33]
When trying to install Juicer with 'sudo gem install juicer', I'm getting the following error:

ERROR:  Error installing juicer:
    juicer requires juicer (>= 0)

Why would this be happening? I have Ruby 1.9.2 and RubyGems 1.8.4 installed.

**Comment by cjohansen** [comment]
Does it work if you specify 1.0.10? Something seems to be broken with my build tool :( try `gem install -v 1.0.10 juicer`

**Comment by ende76** [comment]
I can confirm the issue in Ubuntu 10.04 LTS.

Christian's suggestion for a work-around worked for me.

After I had installed juicer v1.0.10, I've run `gem update`. The upgrade to juicer v.1.0.11 worked without problems.

**Comment by ghost** [comment]
I confirm on Snow Leopard (10.6.7), using ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0] and rubygems 1.8.5. Attempting to install older versions throws the same error.

Not sure what is going on here — not too long ago I installed it on another machine (also 10.6.7 and ruby 1.8.7, but with rubygems 1.4.2). Just for fun I updated rubygems on that machine to 1.8.5, ran gem update juicer and it updated fine.

**Comment by cjohansen** [comment]
The problem was that the tool I use to generate the gemspec insisted on having Juicer a dependency of itself... I've pushed 1.0.12 now, which does not require any previous version of Juicer. Sorry.
