### ISSUE TITLE
option to only verify modified files

### ISSUE THREAD

**Issue by mersayochan** [cjohansen/juicer#34]
I love juicer, but I hate waiting for it verify ALL my files on merge when I have only changed one. It would be great if it used the modified timestamp on the files to detect which ones have been modified after the last merge (using the modified timestamp on the output file if it exists). This would greatly increase the value of this tool for me and should be pretty easy to add.

**Comment by cjohansen** [comment]
It's actually less easy than you think, since Juicer has no cache - thus it knows nothing about which files were changed since last run. Maybe checkout autolint? https://github.com/magnars/autolint
