### ISSUE TITLE
add csslint

### ISSUE THREAD

**Issue by stereobooster** [cjohansen/juicer#35]
https://github.com/stubbornella/csslint
I started it at https://github.com/stereobooster/juicer. But I feel like the refactoring is needed.

**Comment by frankpf** [comment]
I don't think that should be included as a default. 
CSS Lint is an **extremely** optionated tool based on principles of OOCSS, which many don't agree.

**Comment by stereobooster** [comment]
Only 4 rules from 16 have something in share with OOCSS. All other is common. For example: Remove empty rules, Use correct properties for a display and so on. You can turn of rules which you don't agree.

**Comment by cjohansen** [comment]
I don't see a problem with including it as a voluntary binary. Quite the contrary, would be useful in my opinion.

stereobooster: What do you want to refactor? I think it looks pretty good, but it's missing two things: a hook into the binary (which _does_ need refactoring...) and some tests :) What do you think?

**Comment by stereobooster** [comment]
> stereobooster: What do you want to refactor?

I begin to add csslint and find myself copy/pasting code, for me it's a sign... [Take a look](https://github.com/stereobooster/juicer/commit/3d4d73b987b5a15c16c9f9bf1a4fab57ad2e2b63)

**Comment by cjohansen** [comment]
Ah, right. Want to give it a shot? I'd suggest extracting a `Juicer::RhinoBinary` that includes `Juicer::Binary`, but removes the duplication between the Rhino binaries.

**Comment by stereobooster** [comment]
> Ah, right. Want to give it a shot?

I will try if i have time. But I can’t promise anything.
