### ISSUE TITLE
Test suite is failing like it is going out of style

### ISSUE THREAD

**Issue by bcardarella** [cjohansen/juicer#40]
Steps to reproduce:

`git clone https://github.com/cjohansen/juicer.git`
`bundle install`
`gem install turn`
`rake`

I am getting 8 failures and 85 errors.

I suspect there is some dependency I am missing that is causing these errors. Any pointers?

**Comment by bcardarella** [comment]
Not very helpful without the suite output:

https://gist.github.com/1187204

**Comment by cjohansen** [comment]
Hmm, interesting. What version of mocha are you using? The tests are passing locally. Something is probably missing from the automated setup.

**Comment by bcardarella** [comment]
I have version 0.9.12 installed.

**Comment by cjohansen** [comment]
Figured it out. I used to have `rake test:setup` that downloaded some binaries for the tests. That doesn't work anymore, and I had not added two required binaries to the index. Please pull again, and tests should run smoothly (just confirmed on a clean clone).

**Comment by bcardarella** [comment]
Awesome, thanks :)

**Comment by bcardarella** [comment]
I just tried this again with the latest changes and it is still failing.

With Ruby 1.9.2-p290 I get 4 failures and 83 errors: https://gist.github.com/1196862

With Ruby 1.8.7-p334 I get 5 failing tests: https://gist.github.com/1196852

**Comment by bcardarella** [comment]
So this seems to be a dependency issue. I've made this change: https://github.com/bcardarella/juicer/commit/54c70d5e5aeadf31d9248bd6cafc25d39d0ce959

and now only get 1 error with the test suite

```
TestCssCacheBuster:
 test: absolute paths should resolve with document root.  (0.01s) 
    ERROR test: cache busters should add mtime to urls.  (0.01s) 
          ArgumentError: assertion message must be String or Proc, but Juicer::Asset::Path was given.
          /Users/bcardarella/projects/juicer/test/unit/juicer/css_cache_buster_test.rb:83:in `block (3 levels) in <class:TestCssCacheBuster>'
```

**Comment by cjohansen** [comment]
The remaining issue is stil 1.9.1? Care to pull request the environment fix you made?

**Comment by bcardarella** [comment]
Yes, it 1.9.2

**Comment by bcardarella** [comment]
Just sent the pull request
