### ISSUE TITLE
How to set a proxy for yui install?

### ISSUE THREAD

**Issue by portlandtransport** [cjohansen/juicer#46]
I have installed the gem and am at the 'juicer install yui_compressor' step when I get a timeout. I'm pretty sure I'm blocked at my corporate firewall. Do I need to set a proxy somewhere?

**Comment by cjohansen** [comment]
No, Juicer doesn't support that. It's just a regular http download - which version of Juicer are you using?

**Comment by portlandtransport** [comment]
1.0.13

**Comment by cjohansen** [comment]
Seems strange. Are you able to download manually? http://yuilibrary.com/download/yuicompressor/

**Comment by portlandtransport** [comment]
I'm sure I can find a way to download the .zip for the compressor. Once I had it, where would I install it for juicer to use it?

Same question for jslint..

Thanks.

**Comment by cjohansen** [comment]
Well, first of all I'm just trying to figure out what the problem is - if it is a network issue.

**Comment by portlandtransport** [comment]
I'm all set. Needed to set the http_proxy ENV var. Thanks.

**Comment by cjohansen** [comment]
Goodie, glad you figured it out :)
