### ISSUE TITLE
Can juicer recognize already minified files?

### ISSUE THREAD

**Issue by anitagraham** [cjohansen/juicer#47]
I would like to be able to specify somehow that some files are already minified, and that they just need to be included in the final output. For instance 

```
/**
 * @depends jquery-1.6.4.min.js
 * @depends jquery.tools.min.js
 * @depends local-code.js  
 * @depends shared-code.js
 */
```

shouldn't need to check or minify the two .min.js files. Can you suggest a way to do this?

thank you.

**Comment by cjohansen** [comment]
To avoid checking them just pass `-s` (skip) to `juicer merge` - i.e. `juicer merge -s`. To avoid re-minifying them you could use `--minifyer none`, but then nothing would be minified. The proper solution is to not depend on minified sources (i.e. download developer builds instead).
