### ISSUE TITLE
Add possibility to preserve specific comments

### ISSUE THREAD

**Issue by jenshedqvist** [cjohansen/juicer#49]
I think it would be good to be able to add certain comments (such as copyright) to the top of the minified file, as this is supported in JSmin. Preferably with a token of some kind:

 `/*@@ Copyright and maybe path to unminified source */`

becomes:

 `/* Copyright and maybe path to unminified source */`

**Comment by jenshedqvist** [comment]
Nevermind, found that the "!" prefix worked.

**Comment by cjohansen** [comment]
This is up to the minifyer.
