### ISSUE TITLE
Unable to install yui_compressor

### ISSUE THREAD

**Issue by schack** [cjohansen/juicer#52]
juicer install yui_compressor returns

.gem/ruby/1.9.1/gems/juicer-1.0.13/lib/juicer/install/yui_compressor_installer.rb:66:in `latest': undefined method`[]' for nil:NilClass (NoMethodError)
    from /home/henj/.gem/ruby/1.9.1/gems/juicer-1.0.13/lib/juicer/command/install.rb:57:in `version'
    from /home/henj/.gem/ruby/1.9.1/gems/juicer-1.0.13/lib/juicer/command/install.rb:42:in`block in execute'
    from /home/henj/.gem/ruby/1.9.1/gems/juicer-1.0.13/lib/juicer/command/install.rb:39:in `each'
    from /home/henj/.gem/ruby/1.9.1/gems/juicer-1.0.13/lib/juicer/command/install.rb:39:in`execute'
    from /pack/ruby-1.9.3-p125/lib/ruby/gems/1.9.1/gems/cmdparse-2.0.3/lib/cmdparse.rb:436:in `parse'
    from /home/henj/.gem/ruby/1.9.1/gems/juicer-1.0.13/lib/juicer/cli.rb:27:in`parse'
    from /home/henj/.gem/ruby/1.9.1/gems/juicer-1.0.13/lib/juicer/cli.rb:37:in `run'
    from /home/henj/.gem/ruby/1.9.1/gems/juicer-1.0.13/bin/juicer:6:in`<top (required)>'
    from /home/henj/.gem/ruby/1.9.1/bin/juicer:19:in `load'
    from /home/henj/.gem/ruby/1.9.1/bin/juicer:19:in`<main>'

What am I missing ?

**Comment by cjohansen** [comment]
I'm guessing they changed the site markup again? Did the problem persist? Or are you perhaps behind some proxy/firewall?

**Comment by schack** [comment]
Markup hasn't changed, I fixet it with a minor change in the install/Ruby code.
yui_compressor_installer.rb line 63
changed:
webpage = Nokogiri::HTML(open(@website))
to
webpage = Nokogiri::HTML(open(@website).read)

I did the same thing for the other installers.

**Comment by cjohansen** [comment]
Thanks, fixed and released as 1.0.14
