### ISSUE TITLE
jslint nomen option behaves the opposite way it's supposed to

### ISSUE THREAD

**Issue by bensmithett** [cjohansen/juicer#56]
I'm using the `/*jslint nomen: false */` directive to stop JSLint complaining about dangling underscores.

Thing is, according to the [docs](http://www.jslint.com/lint.html) and on the [online linter](http://www.jslint.com/), that behaviour should happen when `nomen: true`.

Not sure if anyone can reproduce this, is it a bug in the old version of JSLint that is bundled with Juicer?

**Comment by cjohansen** [comment]
Seems like your version of JsLint is too old. Try `juicer install jslint` to update.
