### ISSUE TITLE
yui_compressor doesn't install

### ISSUE THREAD

**Issue by craveytrain** [cjohansen/juicer#6]
when installing yui_compressor I get this error:
/Library/Ruby/Gems/1.8/gems/juicer-0.2.5/lib/juicer/install/yui_compressor_installer.rb:64:in `latest': undefined method`get_attribute' for nil:NilClass (NoMethodError)

It looks like Julien isn't hosting the compressor for download on his own site any more (http://www.julienlecomte.net/yuicompressor/) and the URL gets redirected to http://yuilibrary.com/downloads/#yuicompressor.

**Comment by cjohansen** [comment]
Fixed in 0.2.6 which should be on gem servers shortly

**Comment by jsahlen** [comment]
This has broken again – the path for finding the latest version doesn't work anymore. Changing line 63 to the following will do the trick:
`@latest = (webpage / "//h3[@id='yuicompressor']/..//a")[1].text`
