### ISSUE TITLE
Can't install YUI_Compressor

### ISSUE THREAD

**Issue by SirRawlins** [cjohansen/juicer#61]
Morning,

Installed Juice 1.0.17 this morning from gems, and when running 'juicer install yui_compressor' I get the following error:

Robert-Rawlinss-MacBook-Pro:stylesheets robertrawlins$ juicer install yui_compressor
Installing Yui Compressor 2.4.7 in /Users/robertrawlins/.juicer/lib/yui_compressor
Downloading /downloads/yui/yuicompressor/yuicompressor-2.4.7.zip
/Users/robertrawlins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:35:in `initialize': No such file or directory - /downloads/yui/yuicompressor/yuicompressor-2.4.7.zip (Errno::ENOENT)
    from /Users/robertrawlins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:35:in`open'
    from /Users/robertrawlins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:35:in `open'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/gems/juicer-1.0.17/lib/juicer/install/base.rb:134:in`block in download'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/gems/juicer-1.0.17/lib/juicer/install/base.rb:133:in `open'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/gems/juicer-1.0.17/lib/juicer/install/base.rb:133:in`download'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/gems/juicer-1.0.17/lib/juicer/install/yui_compressor_installer.rb:32:in `install'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/gems/juicer-1.0.17/lib/juicer/command/install.rb:49:in`block in execute'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/gems/juicer-1.0.17/lib/juicer/command/install.rb:39:in `each'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/gems/juicer-1.0.17/lib/juicer/command/install.rb:39:in`execute'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/gems/cmdparse-2.0.5/lib/cmdparse.rb:464:in `parse'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/gems/juicer-1.0.17/lib/juicer/cli.rb:27:in`parse'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/gems/juicer-1.0.17/lib/juicer/cli.rb:37:in `run'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/gems/juicer-1.0.17/bin/juicer:6:in`<top (required)>'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/bin/juicer:19:in `load'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/bin/juicer:19:in`<main>'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/robertrawlins/.rvm/gems/ruby-1.9.3-p286/bin/ruby_noexec_wrapper:14:in`<main>'

Any suggestion as to what is going on?

Thanks,

Robert

**Comment by cjohansen** [comment]
Seems like it thinks it downloaded YUI compressor, but really didn't. Did you use sudo when install YUI Compressor? (you shouldn't do that)

**Comment by artlantis** [comment]
Hi,

juicer doesn't install yui_composer in Ubuntu 12.10 edition. Throwing "SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)" message. To workaround this, I did following changes:

   @latest = nil
to
   @latest = "2.4.7" // actual edition of yui_composer

```

   @href = nil
to
   @href = "http://cloud.github.com/downloads/yui/yuicompressor/yuicompressor-2.4.7.zip"

```

   filename = download(@cdn+@href)
to
   filename = download(@href)

after this changes, yui_composer installed properly!

**Comment by cjohansen** [comment]
Want to make this into a patch? :)

**Comment by artlantis** [comment]
Chris, as you wish! :)

**Comment by daniel-lanciana** [comment]
For those that don't know the changes _artlantis_ suggested are made to the file **yui_compressor_installer.rb**, which for me was located at:

...\ruby-1.9.3\lib\ruby\gems\1.9.1\gems\juicer-1.0.18\lib\juicer\install\yui_compressor_installer.rb
