### ISSUE TITLE
rubyzip gem at version 1.0.0 can't be loaded

### ISSUE THREAD

**Issue by endorama** [cjohansen/juicer#71]
After installing juicer I tried to install yui_compressor, but I received an error:

```
$ juicer install yui_compressor
[...] `require': cannot load such file -- zip/zip (LoadError)
[...]
```

As stated in [this StackOverflow](http://stackoverflow.com/a/18630251/715002) question, rubygems installed `rubyzip` 1.0.0, which seems to have compatibility problems. Downgrading to 0.9.9 fixes the error.

Maybe the gemspec could be updated to avoid this problem? :)

**Comment by cjohansen** [comment]
1.0.22 pushed
