### ISSUE TITLE
problems with Rhino

### ISSUE THREAD

**Issue by rafa** [cjohansen/juicer#8]
Hi!
I'm not getting download the Rhino. FTP is timeout. You can put the zip of it here?
Other problem is with "help" command. I write juicer -h or juicer --help and always show me the default screen "available commands". How to help? i'm using the command Vista

BR
Rafael

**Comment by cjohansen** [comment]
This is likely a firewall issue. I'm going to change ftp downloads to http. You can get Rhino here: http://www.mozilla.org/rhino/download.html Put it in $JUICER_HOME/lib (on linux this is ~/.juicer/lib). The help command unfortuntely isn't more helpful currently. I'll help you with any issues you have!

**Comment by cjohansen** [comment]
0.2.6 will no longer use the ftp protocol

**Comment by jakubpawlowicz** [comment]
Had a similar issue and putting Rhino zip file to ~/.juicer/download/rhino/ and then running 'juicer install jslint' did the trick.
