### ISSUE TITLE
fails to install yui_compressor

### ISSUE THREAD

**Issue by grimen** [cjohansen/juicer#9]
<pre>
$ juicer install yui_compressor
/opt/local/lib/ruby/gems/1.8/gems/cjohansen-juicer-0.2.5/lib/juicer/install/yui_compressor_installer.rb:62:in `latest': undefined method `get_attribute' for nil:NilClass (NoMethodError)
    from /opt/local/lib/ruby/gems/1.8/gems/cjohansen-juicer-0.2.5/lib/juicer/command/install.rb:55:in `version'
    from /opt/local/lib/ruby/gems/1.8/gems/cjohansen-juicer-0.2.5/lib/juicer/command/install.rb:40:in `execute'
    from /opt/local/lib/ruby/gems/1.8/gems/cjohansen-juicer-0.2.5/lib/juicer/command/install.rb:37:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/cjohansen-juicer-0.2.5/lib/juicer/command/install.rb:37:in `execute'
    from /opt/local/lib/ruby/gems/1.8/gems/cmdparse-2.0.2/lib/cmdparse.rb:438:in `parse'
    from /opt/local/lib/ruby/gems/1.8/gems/cjohansen-juicer-0.2.5/lib/juicer/cli.rb:27:in `parse'
    from /opt/local/lib/ruby/gems/1.8/gems/cjohansen-juicer-0.2.5/lib/juicer/cli.rb:37:in `run'
    from /opt/local/lib/ruby/gems/1.8/gems/cjohansen-juicer-0.2.5/bin/juicer:8
    from /opt/local/bin/juicer:19:in `load'
    from /opt/local/bin/juicer:19
</pre>

**Comment by cjohansen** [comment]
Possibly a network issue? Could you try again?

**Comment by grimen** [comment]
No, same.

**Comment by cjohansen** [comment]
Could you try from master? I've replaced Hpricot with Nokogiri, but it shouldn't matter. It works here. Also, try to wget the URL manually, see what you get.

**Comment by grimen** [comment]
The master gemspec is invalid - looked for files that don't exist. Everything works fine after re-generating gemspec and build/install the gem. =)

**Comment by cjohansen** [comment]
Closing this
